name: umeas
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Cool icons
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  # Firebase stuff
  firebase_core: ^2.9.0
  # Documentation
  dartdoc: ^6.2.1
  # Value equality
  equatable: ^2.0.5
  # Functional programming - either types
  dartz: ^0.10.1
  # State management
  flutter_bloc: ^8.1.2
  # Dependency injection
  get_it: ^7.2.0
  bloc_test: ^9.1.1
  firebase_auth: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linting
  flutter_lints: ^2.0.0
  # Static code analysis
  dart_code_metrics: ^5.7.2
  # Mocking in tests
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/images/um_logo.png
    - assets/images/umeas_text_only.png
    - assets/images/umeas_verbose.png