name: umeas
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.9.0
  # Documentation
  dartdoc: ^6.2.1
  # Value equality
  equatable: ^2.0.5
  # Functional programming - either types
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.2
  integration_test: ^0.8.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/images/um_logo.png
    - assets/images/umeas_text_only.png
    - assets/images/umeas_verbose.png