// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEtUKDQdxIqQJCLFOnDZ2mgSPWhVJasUQ',
    appId: '1:936924852215:android:7993be976a6390902a08f2',
    messagingSenderId: '936924852215',
    projectId: 'pc-api-7023893375490366569-24',
    databaseURL:
        'https://pc-api-7023893375490366569-24-default-rtdb.firebaseio.com',
    storageBucket: 'pc-api-7023893375490366569-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnEV_Jsq-umw361cH7jna9H1v8C5MsfgI',
    appId: '1:936924852215:ios:0222437dec9433362a08f2',
    messagingSenderId: '936924852215',
    projectId: 'pc-api-7023893375490366569-24',
    databaseURL:
        'https://pc-api-7023893375490366569-24-default-rtdb.firebaseio.com',
    storageBucket: 'pc-api-7023893375490366569-24.appspot.com',
    androidClientId:
        '936924852215-k6fpbrn5eu99v2rukg0eqas7gjnmvtdh.apps.googleusercontent.com',
    iosClientId:
        '936924852215-qkl27so2u6jbqr69fiqtk9o4m6v82sqq.apps.googleusercontent.com',
    iosBundleId: 'xyz.wjcblair.umeas',
  );
}
