name: Continuous Integration Workflow

on:
  workflow_call:
    inputs:
      flavor:
        required: true
        type: string
    secrets:
      PAT:
        required: true

jobs:
  setup:
    name: Base workflow setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Restore packages
        run: flutter pub get

  analyze:
    name: Analyze
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Restore packages
        run: flutter pub get

      - name: Run analysis
        run: flutter analyze

  test:
    name: Run tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Restore packages
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test --coverage --flavor ${{ inputs.flavor }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
