name: Feature Branch CI

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'development'

jobs:
  build_and_test:
    uses: ./.github/workflows/harden-and-setup.yaml
    with:
      flavor: dev
