name: Hotfix Branch Workflow

on:
  push:
    branches:
      - 'hotfix/*'
  pull_request:
    branches:
      - 'production'
      - 'development'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Call Harden Security and Run Base Workflow
        uses: ./.github/workflows/harden-and-setup.yaml
        with:
          flavor: dev

  # fix_and_test:
  #   runs-on: ubuntu-latest
  #   steps:
      # Build app
      # Run tests
      # Report code coverage
      # Linting and static analysis
